### ISSUE TITLE
webpack.base.conf.js

### ISSUE THREAD

**Issue by hankaibo** [jusfoun-FE/spa-development-PC#6]
[这个](https://github.com/jusfoun-FE/spa-development-PC/blob/master/build/webpack.base.conf.js#L40)和[这个](https://github.com/jusfoun-FE/spa-development-PC/blob/master/build/webpack.base.conf.js#L43)别名定义好象是多余的，请确认。

**Comment by zhu18** [comment]
@ws880321 @weibsgz
